#version: '3'
#
#services:
#  mongo01:
#    # 镜像
#    image: mongo:latest
#    restart: always
#    container_name: mongo01
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: Kyralo991010
#    volumes:
#      - "/data/mongo/db01:/data/db"

#  内存占用太大
#  es01:
#    # 镜像
#    image: elasticsearch:7.5.1
#    restart: always
#    container_name: es01
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - discovery.type=single-node
#      - cluster.name=amall-es01
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#
#  lg01:
#    # 镜像
#    image: logstash:7.5.1
#    restart: always
#    container_name: lg01
#    ports:
#      - "5044:5044"
#    volumes:
#      - /data/logstash/lg01/config:/usr/share/logstash/config
#      - /data/logstash/lg01/conf:/usr/share/logstash/conf
#      - /data/logstash/lg01/jar:/usr/share/logstash/jar
#      - /data/logstash/lg01/sh:/usr/share/logstash/sh
#      - /data/logstash/lg01/sh:/usr/share/logstash/sql
#      - /data/logstash/lg01/sh:/usr/share/logstash/template
#      - /data/logstash/lg01/pipeline:/usr/share/logstash/pipeline
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#      networks:
#        - amall
#
#networks:
#  amall:
#    external: true